import { api } from '../../utils/api';

/**
 * Route handler for /sitemap.xml
 * Proxies the sitemap generated by the CMS API.
 */
export async function GET() {
    try {
        const sitemap = await api.getGenerateSitemap();
        
        if (!sitemap) {
            return new Response('Error generating sitemap', { status: 500 });
        }

        return new Response(sitemap, {
            headers: {
                'Content-Type': 'application/xml',
                'Cache-Control': 'public, s-maxage=86400, stale-while-revalidate=3600',
            },
        });
    } catch (error) {
        console.error('Error in sitemap route:', error);
        return new Response('Internal Server Error', { status: 500 });
    }
}
